#                            -*- mode: org; -*-
#
#+TITLE: *PatMat: SPITBOL-like pattern construction and matching in C++*
#+AUTHOR: nil
#+OPTIONS: author:nil email:nil ^:{}
#+LaTeX_HEADER: \usepackage[parfill]{parskip}
#+STARTUP: hidestars odd

* [[file:COPYING][Copyright]]
  + Copyright (C) 2013 Henry G. Weller
  + Copyright (C) 2007,2008, Philip L. Budne
  + Copyright (C) 1998-2005, AdaCore

* Original Sources
  + [[http://www.snobol4.org/spipat/][SPIPAT]]
  + [[http://www2.adacore.com/gap-static/GNAT_Book/html/rts/g-spipat__adb.htm][GNAT.SPITBOL.PATTERNS]] [[Doc/Ada/g-spipat.ads][g-spipat.ads]] [[Doc/Ada/g-spipat.adb][g-spipat.adb]]
  + [[https://github.com/hardbol/spitbol][SPITBOL]]
  This software and documentation is developed from both the =SPIPAT= C/C++
  package of Philip L. Budne and the original =GNAT.SPITBOL.PATTERNS= package of
  GNU Ada based on =Macro-SPITBOL= created by Robert Dewar.  GNAT was originally
  developed by the GNAT team at New York University with extensive contributions
  provided by Ada Core Technologies Inc.

  This is a completely general patterm matching package based on the pattern
  language of =SNOBOL4=, as implemented in =SPITBOL=. The pattern language is
  modeled on context free grammars, with context sensitive extensions that
  provide full (type 0) computational capabilities.

* Documentation
  + [[file:Doc/Tutorial.html][Tutorial]]
  + [[file:Doc/TODO.html][TODO]]
* Build and Test
  The default build setup is to compile with =g++= but =PatMat= has also been
  tested with =clang++= and any other standard C++ compiler should be suitable.
  The particular compiler can be configured by editing =Make/Makefile.config=.
  + To build the PatMat library: =make=
  + To run all the tests: =make test=
  + To run the tutorial examples: =make tutorial=
