#                            -*- mode: org; -*-
#
#+TITLE: *PatMat: SPITBOL-like pattern construction and matching in C++*
#+AUTHOR: nil
#+OPTIONS: author:nil email:nil ^:{}
#+LaTeX_HEADER: \usepackage[parfill]{parskip}
#+STARTUP: hidestars odd

* [[http://henry.github.com/PatMat/COPYING][Copyright]]
  + Copyright (C) 2013 Henry G. Weller
  + Copyright (C) 2007,2008, Philip L. Budne
  + Copyright (C) 1998-2005, AdaCore

* Original Sources
  This documentation (and the underlying software) developed from the
  GNAT.SPITBOL.PATTERNS package of GNU Ada.  GNAT was originally developed by
  the GNAT team at New York University.  Extensive contributions were provided
  by Ada Core Technologies Inc.

  SPITBOL-like pattern construction and matching

  This child package of GNAT.SPITBOL provides a complete implementation of the
  SPITBOL-like pattern construction and matching operations. This package is
  based on Macro-SPITBOL created by Robert Dewar.

  This is a completely general patterm matching package based on the pattern
  language of SNOBOL4, as implemented in SPITBOL. The pattern language is
  modeled on context free grammars, with context sensitive extensions that
  provide full (type 0) computational capabilities.

* Documentation
  + [[http://henry.github.com/PatMat/Doc/Tutorial.html][Tutorial]]
  + [[http://henry.github.com/PatMat/Doc/TODO.html][TODO]]
