### Copyright 2013-2016 Henry G. Weller
###-----------------------------------------------------------------------------
##  This file is part of
### ---     The PatMat Pattern Matcher
###-----------------------------------------------------------------------------
##
##  PatMat is free software: you can redistribute it and/or modify it under the
##  terms of the GNU General Public License version 2 as published by the Free
##  Software Foundation.
##
##  PatMat is distributed in the hope that it will be useful, but WITHOUT ANY
##  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
##  FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
##  details.
##
##  You should have received a copy of the GNU General Public License along with
##  this program.  If not, see <http://www.gnu.org/licenses/>.
##
###-----------------------------------------------------------------------------
### Title: General make configuration file
###  Maintainer: Henry G. Weller
###-----------------------------------------------------------------------------

###-----------------------------------------------------------------------------
### Identification and inclusion of the default build environment
###-----------------------------------------------------------------------------
ifndef BUILDENV
   BUILDENV=$(BUILDENV_$(shell uname -s))
   BUILDENV_Linux=linux
endif

###-----------------------------------------------------------------------------
### Set the default target
###-----------------------------------------------------------------------------
# TARGET = default | opt | debug
TARGET = default

###-----------------------------------------------------------------------------
### Set directories and general macros
###-----------------------------------------------------------------------------
ifndef DIR
    # The cd ./ in FULLDIR is for a corner case where . is a symbolic link
    # At least with bash (not sure with other shells), pwd returns me
    # the symbolic link path (as for BASEDIR), rather than the physical path
    # So this is necessary for the substitution to happen correctly. Ugh!
    BASEDIR=    $(shell cd ./$(PW_DIR); pwd)
    FULLDIR=	$(shell cd ./; pwd)
    DIR=        $(subst $(BASEDIR),,$(FULLDIR))
endif

LIBDIR=$(PM_DIR)/platforms/$(BUILDENV)/$(TARGET)
LIB=PatMat
LIBSO=$(LIBDIR)/lib$(LIB).so

###-----------------------------------------------------------------------------
### Compilation flags
###-----------------------------------------------------------------------------
DFLAGS_none = -O1
DFLAGS_opt = -O3
DFLAGS_debug = -g

#CXX = g++
CXX = clang++
CXXFLAGS = -I. -I$(PM_DIR) -Wall -Wextra -Wno-unused-parameter -Wold-style-cast

###-----------------------------------------------------------------------------
### Documentation build commands
###-----------------------------------------------------------------------------
.SUFFIXES: .org .html .pdf
.org.html:
	eemacs $< --batch --eval "(org-html-export-to-html)"
.org.pdf:
	eemacs $< --batch --eval "(org-latex-export-to-pdf)"

###-----------------------------------------------------------------------------
